### ISSUE TITLE
Property "..." does not exist on value ot type "....."

### ISSUE THREAD

**Issue by dominicosavio** [PureMVC/puremvc-typescript-multicore-framework#1]
I am using this framework and ran into these errors. Not sure what cause:

error TS2094: The property 'registerMediator' does not exist on value of type '() => puremvc.IFacade'
error TS2094: The property 'retrieveProxy' does not exist on value of type '() => puremvc.IFacade'
error TS2094: The property 'registerProxy' does not exist on value of type '() => puremvc.IFacade'

Any idea on how to fix these error? By the way, the d.ts file is kinda out of date too.

**Comment by saadshams** [comment]
Published a brand new update. This should have fixed the issue.
