### ISSUE TITLE
how、

### ISSUE THREAD

**Issue by devxi** [PureMVC/puremvc-typescript-multicore-framework#10]

**Comment by devxi** [comment]
![image](https://user-images.githubusercontent.com/42086028/59594841-33c7e080-9127-11e9-8670-484e16e74ae7.png)
in my ts project， in Main.ts , i try use import puremvc from "../libs/puremvc/bin/puremvc-typescript-multicore-1.1" to user it , but i got a wrong in vscode:file "../libs/puremvc/bin/puremvc-typescript-multicore-1.1" is not a module

**Comment by cliffhall** [comment]
@devxi Looks like the underlined file path is invalid?
