### ISSUE TITLE
Typescript 0.9 Compatibility

### ISSUE THREAD

**Issue by systemsymbiosis** [PureMVC/puremvc-typescript-multicore-framework#3]
The ant build is failing with the following error.

     [exec] /puremvc-typescript-multicore-framework/src/org/puremvc/typescript/multicore/patterns/command/MacroComm
and.ts(48,35): error TS2068: 'new T[]' cannot be used to create an array. Use 'new Array<T>()' instead.
     [exec] /puremvc-typescript-multicore-framework/src/org/puremvc/typescript/multicore/patterns/mediator/Mediator
.ts(103,21): error TS2068: 'new T[]' cannot be used to create an array. Use 'new Array<T>()' instead.
     [exec] Result: 1

Fix 

In  /puremvc-typescript-multicore-framework/src/org/puremvc/typescript/multicore/patterns/command/MacroCommand.ts to:

		constructor()
		{
			super();

			this.subCommands = new Array<Function>();
			this.initializeMacroCommand();
		}

Fix

In  /puremvc-typescript-multicore-framework/src/org/puremvc/typescript/multicore/patterns/mediator/Mediator the listNotifications method to:

		listNotificationInterests():string[]
		{
			return new Array<string>();
		}

These fixes build the project at least, although I am not 100% sure they are correct.

I'll be happy to make a pull request and try and fix this issue if you want.

**Comment by cliffhall** [comment]
User sparkbuzz has recently made changes that seem to bring the framework up to date. Can you see if this fixes your issue, or otherwise submit a pull request for the changes you made?

**Comment by systemsymbiosis** [comment]
@cliffhall I made some changes related to this issue a while back and they got merged into the main branch. I'll close it now. Thanks for paying attention to it!
