### ISSUE TITLE
will this be updated?

### ISSUE THREAD

**Issue by jcyuan** [PureMVC/puremvc-typescript-multicore-framework#8]
cause typescript is really popular now, and it supports `protected`, `abstract` etc keywords now, so I think PureMvc should have a proper update as well...

@cliffhall what do you think?

**Comment by cliffhall** [comment]
There are a number of protected methods in the AS3 reference implementation, and it would be good if we could more closely match the reference with Typescript. Would you like to make a PR?

Cheers,
-=Cliff>
